export const SIGNUP = 'SIGNUP'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'

export const SIGNIN = 'SIGNIN'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE'

export const LOGOUT = 'LOGOUT'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

export const DEMO = 'DEMO';
export const DEMO_SUCCESS = 'DEMO_SUCCESS'
export const DEMO_FAILURE = 'DEMO_FAILURE'

export const SECOND_DEMO = 'SECOND_DEMO';
export const SECOND_DEMO_SUCCESS = 'SECOND_DEMO_SUCCESS'
export const SECOND_DEMO_FAILURE = 'SECOND_DEMO_FAILURE'
